<?xml version="1.0"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://localhost/ToCode3-2/WS-TD/InfoStudent-server.php" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="InfoStudent" targetNamespace="http://localhost/ToCode3-2/WS-TD/InfoStudent-server.php">
  <types>
    <xsd:schema targetNamespace="http://localhost/ToCode3-2/WS-TD/InfoStudent-server.php">
      <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
    </xsd:schema>
  </types>
  <portType name="InfoStudentPort">
    <operation name="getInfoStudent">
      <input message="tns:getInfoStudentIn"/>
    </operation>
  </portType>
  <binding name="InfoStudentBinding" type="tns:InfoStudentPort">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="getInfoStudent">
      <soap:operation soapAction="http://localhost/ToCode3-2/WS-TD/InfoStudent-server.php#getInfoStudent"/>
      <input>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost/ToCode3-2/WS-TD/InfoStudent-server.php"/>
      </input>
      <output>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://localhost/ToCode3-2/WS-TD/InfoStudent-server.php"/>
      </output>
    </operation>
  </binding>
  <message name="getInfoStudentIn">
    <part name="cin" type="xsd:anyType"/>
  </message>
  <service name="InfoStudentService">
    <port name="InfoStudentPort" binding="tns:InfoStudentBinding">
      <soap:address location="http://localhost/ToCode3-2/WS-TD/InfoStudent-server.php"/>
    </port>
  </service>
</definitions>
